-- Tabela EMPRESA
CREATE TABLE EMPRESA (
    EMPRESA_CNPJ VARCHAR(20) PRIMARY KEY,
    EMPRESA_NOME VARCHAR(100),
    EMPRESA_ENDERECO VARCHAR(150),
    EMPRESA_TELEFONE VARCHAR(20)
)

-- Tabela USUARIO
CREATE TABLE USUARIO (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_CPF VARCHAR(14) UNIQUE,
    USER_NOME VARCHAR(100),
    USER_DT_NASC DATE,
    USER_ENDERECO VARCHAR(150),
    USER_CEP VARCHAR(15),
    USER_CELULAR VARCHAR(20),
    USER_TELEFONE VARCHAR(20),
    USER_TIPO VARCHAR(50),
    EMPRESA_CNPJ VARCHAR(20),
    FOREIGN KEY (EMPRESA_CNPJ) REFERENCES EMPRESA(EMPRESA_CNPJ)
)

-- Tabela ACOMODACAO
CREATE TABLE ACOMODACAO (
    ACOMO_ID INT IDENTITY(1,1) PRIMARY KEY,
    ACOMO_END VARCHAR(150),
    ACOMO_TIPO VARCHAR(50),
    ACOMO_DISPONIBILIDADE BIT,
    ACOMO_ANFITRIAO VARCHAR(100),
    ACOMO_CAPACIDADE INT,
    ACOMO_ESTADO VARCHAR(50),
    ACOMO_CIDADE VARCHAR(50),
    ACOMO_PAIS VARCHAR(50)
)

-- Tabela RESERVA
CREATE TABLE RESERVA (
    RESERVA_ID INT IDENTITY(1,1) PRIMARY KEY,
    RESERVA_QTD_HOSPEDE INT,
    RESERVA_CHECKIN DATE,
    RESERVA_CHECKOUT DATE,
    RESERVA_VALOR DECIMAL(10,2),
    USER_ID INT,
    ACOMO_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(USER_ID),
    FOREIGN KEY (ACOMO_ID) REFERENCES ACOMODACAO(ACOMO_ID)
)

-- Tabela PAGAMENTO
CREATE TABLE PAGAMENTO (
    PAG_ID INT IDENTITY(1,1) PRIMARY KEY,
    RESERVA_ID INT,
    PAG_TIPO_TRANS VARCHAR(50),
    PAG_DATA_TRANS DATE,
    PAG_DADOS_BANC VARCHAR(100),
    FOREIGN KEY (RESERVA_ID) REFERENCES RESERVA(RESERVA_ID)
)


------------------------------------------------------------------------------





-- Tabela DESTINO (adicionada para viabilizar a avalia  o)
CREATE TABLE DESTINO (
    DESTINO_ID INT IDENTITY(1,1) PRIMARY KEY,
    DESTINO_NOME VARCHAR(100),
    DESTINO_DESCRICAO TEXT
)

-- Atualizando a tabela ACOMODACAO para incluir rela  o com DESTINO
ALTER TABLE ACOMODACAO
ADD DESTINO_ID INT,
    FOREIGN KEY (DESTINO_ID) REFERENCES DESTINO(DESTINO_ID);

-- Tabela AVALIACAO_DESTINO
CREATE TABLE AVALIACAO_DESTINO (
    AVDST_ID INT IDENTITY(1,1) PRIMARY KEY,
    DESTINO_ID INT,
    USER_ID INT,
    AVDST_COMUNICACAO INT CHECK (AVDST_COMUNICACAO BETWEEN 1 AND 5),
    AVDST_ANUNCIO INT CHECK (AVDST_ANUNCIO BETWEEN 1 AND 5),
    AVDST_CHECKIN INT CHECK (AVDST_CHECKIN BETWEEN 1 AND 5),
    AVDST_LOCALIZACAO INT CHECK (AVDST_LOCALIZACAO BETWEEN 1 AND 5),
    AVDST_LIMPEZA INT CHECK (AVDST_LIMPEZA BETWEEN 1 AND 5),
    AVDST_COMENTARIO TEXT,
    DATA_AVALIACAO DATE DEFAULT GETDATE(),
    FOREIGN KEY (DESTINO_ID) REFERENCES DESTINO(DESTINO_ID),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(USER_ID)
);




ALTER TABLE EMPRESA
ADD EMPRESA_NOME_FANTASIA VARCHAR(100);


ALTER TABLE EMPRESA
ADD EMPRESA_ATIVIDADE VARCHAR(100);



CREATE TABLE TIPO_USUARIO (
    USER_ID INT,
    TIPO_USUARIO VARCHAR(50),
    PRIMARY KEY (USER_ID, TIPO_USUARIO),
    FOREIGN KEY (USER_ID) REFERENCES USUARIO(USER_ID)
);




--------------------------TESTES------------------------------

INSERT INTO EMPRESA (
    EMPRESA_CNPJ, EMPRESA_NOME, EMPRESA_NOME_FANTASIA, EMPRESA_ENDERECO, EMPRESA_TELEFONE, EMPRESA_ATIVIDADE
) VALUES (
    '12.345.678/0001-00',
    'Reserva J  LTDA',
    'Reserva J ',
    'Rua Harmonia, 123 - Vila Madalena, S o Paulo - SP',
    '(11) 99999-9999',
    'Plataforma digital de reservas de hospedagens de curta temporada'
);


SELECT * FROM EMPRESA



INSERT INTO USUARIO (
    USER_CPF, USER_NOME, USER_DT_NASC, USER_ENDERECO, USER_CEP, USER_CELULAR, USER_TELEFONE, EMPRESA_CNPJ
) VALUES (
    '123.456.789-00',
    'Pedro Dias',
    '1992-08-15',
    'Rua Fradique Coutinho, 456 - S o Paulo - SP',
    '05416-000',
    '(11) 91234-5678',
    '(11) 3232-1111',
    '12.345.678/0001-00'
);

SELECT * FROM USUARIO


INSERT INTO TIPO_USUARIO (
    USER_ID, TIPO_USUARIO
) VALUES (
    1, 'Anfitri o'
);


SELECT * FROM TIPO_USUARIO


INSERT INTO DESTINO (
    DESTINO_NOME, DESTINO_DESCRICAO
) VALUES (
    'Vila Madalena - S o Paulo',
    'Bairro cultural e bo mio conhecido por arte urbana, bares, caf s e f cil acesso ao metr .'
);


SELECT * FROM DESTINO


INSERT INTO ACOMODACAO (
    ACOMO_END, ACOMO_TIPO, ACOMO_DISPONIBILIDADE, ACOMO_ANFITRIAO,
    ACOMO_CAPACIDADE, ACOMO_ESTADO, ACOMO_CIDADE, ACOMO_PAIS, DESTINO_ID
)
VALUES (
    'Rua Harmonia, 321 - Vila Madalena',
    'Apartamento',
    1,
    'Pedro Dias',
    2,
    'SP',
    'S o Paulo',
    'Brasil',
    1 -- certifique-se que j  exista um DESTINO com ID = 1
);


SELECT * FROM ACOMODACAO


INSERT INTO RESERVA (
    RESERVA_QTD_HOSPEDE,
    RESERVA_CHECKIN,
    RESERVA_CHECKOUT,
    RESERVA_VALOR,
    USER_ID,
    ACOMO_ID
)
VALUES (
    2,
    '2025-06-10',
    '2025-06-15',
    1250.00,
    1,
    3
);


SELECT * FROM RESERVA



INSERT INTO PAGAMENTO (
    RESERVA_ID,
    PAG_TIPO_TRANS,
    PAG_DATA_TRANS,
    PAG_DADOS_BANC
)
VALUES (
    2,
    'PIX',
    '2025-06-15',
    'Chave: pedrodias@email.com'
);




SELECT * FROM PAGAMENTO


INSERT INTO AVALIACAO_DESTINO (
    DESTINO_ID, AVDST_COMUNICACAO, AVDST_ANUNCIO, AVDST_CHECKIN, AVDST_LOCALIZACAO, AVDST_LIMPEZA
) VALUES (
    1, 5, 5, 4, 5, 4
);


SELECT * FROM AVALIACAO_DESTINO